title: Token Dashboard
email: dortcorm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Token Dashboard Web3
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  learn:
    output: true
    permalink: /learn/:path
redirects: yes
